version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-sql-canlogger-mosquitto
    ports:
      - "1883:1883"
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h 127.0.0.1 -t '$$SYS/#' -C 1 -W 3 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16
    container_name: mqtt-sql-canlogger-db
    environment:
      POSTGRES_DB: candb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  logger:
    build: ./mqtt_logger
    container_name: mqtt-sql-canlogger-logger
    depends_on:
      mosquitto:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      DB_HOST: db
      DB_NAME: candb
      DB_USER: user
      DB_PASS: password
      MQTT_HOST: mosquitto
    restart: unless-stopped

  publisher:
    build: ./mqtt_publisher
    container_name: mqtt-sql-canlogger-publisher
    depends_on:
      mosquitto:
        condition: service_healthy
    environment:
      MQTT_HOST: mosquitto
    restart: unless-stopped

  api:
    build: ./mqtt_api
    container_name: mqtt-sql-canlogger-api
    depends_on:
      db:
        condition: service_started
    environment:
      DB_HOST: db
      DB_NAME: candb
      DB_USER: user
      DB_PASS: password
    ports:
      - "5000:5000"
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: mqtt-sql-canlogger-web
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html:ro
      - ./web/script.js:/usr/share/nginx/html/script.js:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
  mosquitto_data:
